[mongodb]
localhost

[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[catalogue]
localhost

[cart]
localhost

[user]
localhost

[shipping]
localhost

[payment]
localhost

[frontend]
localhost


[local]
localhost

[all:vars]
ansible_user=ec2-ansible-user
ansible_password=DevOps321

[local:vars]
COURSE=Ansible
DURATION=10HRS
TRAINER=Siva
NAME=from inventory
