[mongodb]
localhost

[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[catalogue]
catalogue.daws87s.fun

[cart]
cart.daws87s.fun

[user]
user.daws87s.fun

[shipping]
shipping.daws87s.fun

[payment]
payment.daws87s.fun

[frontend]
frontend.daws87s.fun


[local]
localhost

[all:vars]
ansible_user=ec2-ansible-user
ansible_password=DevOps321

[local:vars]
COURSE=Ansible
DURATION=10HRS
TRAINER=Siva
NAME=from inventory
